FROM node:17-bullseye-slim as vite
# WORKDIR /app
# RUN npm create vite@latest vue-ts-example -- --template vue-ts
# RUN cd vue-ts-example && npm i
# COPY vite.config.ts vue-ts-example/vite.config.ts
# WORKDIR /app/vue-ts-example
# CMD npm run dev